/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#001f23",
        "tertiary": "#713d10",
        "surface-container-high": "#334155",
        "primary": "#2dd4bf",
        "surface-container-highest": "#475569",
        "surface-bright": "#1e293b",
        "surface-dim": "#0f172a",
        "on-primary-fixed-variant": "#004f56",
        "on-secondary-fixed": "#00201e",
        "surface": "#0f172a",
        "on-secondary-fixed-variant": "#00504b",
        "primary-fixed": "#9ff0fb",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#301400",
        "secondary-fixed": "#acefe7",
        "on-error-container": "#93000a",
        "surface-tint": "#006972",
        "primary-fixed-dim": "#82d3de",
        "primary-container": "#006d77",
        "background": "#0b1121",
        "secondary": "#236863",
        "on-background": "#f8fafc",
        "tertiary-fixed": "#ffdcc5",
        "on-primary": "#042f2e",
        "on-tertiary-fixed-variant": "#6d390c",
        "secondary-container": "#a9ece5",
        "surface-container": "#1e293b",
        "tertiary-fixed-dim": "#ffb783",
        "on-surface": "#f8fafc",
        "tertiary-container": "#8e5426",
        "surface-variant": "#334155",
        "inverse-primary": "#82d3de",
        "outline": "#94a3b8",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary": "#ffffff",
        "surface-container-low": "#0b1121",
        "on-secondary-container": "#286d67",
        "error": "#ba1a1a",
        "on-primary-container": "#9becf7",
        "surface-container-lowest": "#020617",
        "on-surface-variant": "#cbd5e1",
        "on-tertiary-container": "#ffd7bd",
        "secondary-fixed-dim": "#90d3cb",
        "outline-variant": "#475569",
        "error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1440px",
        "gutter": "24px",
        "xl": "80px",
        "md": "24px",
        "xs": "4px",
        "base": "8px",
        "lg": "48px",
        "sm": "12px",
        "margin-mobile": "16px",
        "margin-desktop": "64px"
      },
      "fontFamily": {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
